- name: check if kubectl exists
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl

- name: check if kubectx exists
  stat:
    path: /usr/local/bin/kubectx
  register: kubectx

- name: check if kubens exists
  stat:
    path: /usr/local/bin/kubens
  register: kubens

- name: Get the lastest version of kubectl
  uri:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    return_content: yes    
  register: kubectl_version 

- name: Download and Install kubernetes tools
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: 0755
  loop:
    - { url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.content| replace('\n','') }}/bin/linux/amd64/kubectl", dest: /usr/local/bin/kubectl }
    - { url: "https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx", dest: /usr/local/bin/kubectx }
    - { url: "https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens", dest: /usr/local/bin/kubens }
  notify: Install autocompletion