---
- name: Include variables
  include_vars: 
    dir: vars
    extensions: 
      - yaml
      - yml

- name: Load package facts
  package_facts:
    manager: "auto"  

- include_tasks: "{{ task_name }}"
  with_fileglob: ./tasks/{{ansible_distribution}}/*.yml
  loop_control:
    loop_var: "task_name"