---
- name: Include variables
  include_vars: 
    dir: vars
    extensions: 
      - yaml
      - yml

- name: Install All Basics Packages
  apt:
    name: "{{  item  }}"
    state: present
  loop: "{{ packages }}"
  become: true

- name: Load package facts
  package_facts:
    manager: "auto"  

- name: Install Chrome if is not installed
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: "'google-chrome-stable' not in ansible_facts.packages"