---
- name: Include variables
  include_vars: 
    dir: vars
    extensions: 
      - yaml
      - yml

- name: Load package facts
  package_facts:
    manager: "auto"  

- name: Install All Basic Packages
  apt:
    name: "{{  item  }}"
    state: present
  when: "item not in ansible_facts.packages"  
  loop: "{{ packages }}"
  become: true

- name: Install Chrome if is not installed
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: "'google-chrome-stable' not in ansible_facts.packages"

- name: Add key, for docker repository
  apt_key:
    id: 0EBFCD88
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker engine
  apt:
    name: "{{ item }}"
    state: present
  when: "item not in ansible_facts.packages"
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: Add key, for Vscode repository
  apt_key:    
    url:  https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Vscode repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present

- name: Install Vscode
  apt:
    name: "{{ item }}"
    state: present
  when: "item not in ansible_facts.packages"
  loop:
    - code