---
- name: Include variables
  include_vars: 
    dir: vars
    extensions: 
      - yaml
      - yml

- name: Load package facts
  package_facts:
    manager: "auto"  

- include_tasks: "{{ item }}"
  with_fileglob: ./tasks/*.yml